### ISSUE TITLE
Add support for site's supported versions of SSL, TLS etc

### ISSUE THREAD

**Issue by patkaehuaea** [kbfastcat/poll#1]
I sometimes find myself diagnosing certificate and supported security protocol issues. Any chance this is something that could be looked into?

**Comment by kbfastcat** [comment]
@patkaehuaea I think this is what you are looking for [readme](https://github.com/kbfastcat/poll/blob/master/README.md)

**Comment by kbfastcat** [comment]
This should be what you wanted...

**Comment by patkaehuaea** [comment]
Perfect, thanks @kbfastcat!
